name: matrix
on: push

jobs:
    deploy:
        strategy:
            matrix:
                os: [ubuntu-latest, ubuntu-20.04, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:
            - name: echo docker details
              run: echo "${{ matrix.os }}"

